import { existsSync, writeFileSync, readFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import { homedir } from 'os';
import { getHookDispatcherPath, getSharedHooksDir } from '../runtime/runtime-paths';

const KNOWN_HOOK_FILENAMES = ['netior-session-hook.mjs', 'netior-dev-session-hook.mjs'];

/**
 * Creates the shared hook dispatcher at %APPDATA%/netior/data/hooks/netior-session-hook.mjs.
 * Called by Claude Code's hooks (SessionStart, SessionEnd, UserPromptSubmit, Stop).
 */
export function setupHookScript(): void {
  const hooksDir = getSharedHooksDir();
  mkdirSync(hooksDir, { recursive: true });

  const hookPath = getHookDispatcherPath();

  const script = `#!/usr/bin/env node
// Auto-generated by Netior ??do not edit manually.
// Called by Claude Code hooks (SessionStart / SessionEnd / UserPromptSubmit / Stop).
// Usage: node netior-session-hook.mjs [start|stop|prompt|response-stop]

import { readFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import http from 'http';

const TIMEOUT_MS = 2000;
const __dirname = dirname(fileURLToPath(import.meta.url));

function resolvePort() {
  const runtimeScope = (process.env.NETIOR_RUNTIME_SCOPE || '').trim();
  const runtimeInstanceId = (process.env.NETIOR_RUNTIME_INSTANCE_ID || '').trim();
  if (!runtimeScope || !/^[a-z0-9._-]+$/i.test(runtimeScope)) {
    return null;
  }

  const candidates = [];
  if (runtimeInstanceId && /^[a-z0-9._-]+$/i.test(runtimeInstanceId)) {
    candidates.push(join(__dirname, 'runtimes', runtimeScope, runtimeInstanceId, 'port'));
  }
  candidates.push(join(__dirname, 'runtimes', runtimeScope, 'port'));

  for (const candidate of candidates) {
    try {
      const portText = readFileSync(candidate, 'utf-8').trim();
      const port = parseInt(portText, 10);
      if (Number.isFinite(port) && port > 0) {
        return port;
      }
    } catch {
      // Try the next candidate.
    }
  }

  return null;
}

async function main() {
  const hookType = process.argv[2] || 'start';

  // Only run inside Netior PTY
  const ptyId = process.env.NETIOR_PTY_ID;
  if (!ptyId) process.exit(0);
  const port = resolvePort();
  if (!port) process.exit(0);

  // Read stdin (Claude provides JSON)
  let input = '';
  try {
    input = readFileSync(0, 'utf-8');
  } catch {
    process.exit(0);
  }

  let data;
  try {
    data = JSON.parse(input);
  } catch {
    process.exit(0);
  }

  let payload;
  let endpoint;

  switch (hookType) {
    case 'start':
      payload = JSON.stringify({
        netior_pty_id: ptyId,
        session_id: data.session_id || null,
      });
      endpoint = '/hook/session-start';
      break;
    case 'stop':
      payload = JSON.stringify({
        netior_pty_id: ptyId,
      });
      endpoint = '/hook/session-stop';
      break;
    case 'prompt':
      payload = JSON.stringify({
        netior_pty_id: ptyId,
      });
      endpoint = '/hook/prompt-submit';
      break;
    case 'response-stop':
      payload = JSON.stringify({
        netior_pty_id: ptyId,
      });
      endpoint = '/hook/stop';
      break;
    default:
      process.exit(0);
  }

  return new Promise((resolve) => {
    const timer = setTimeout(() => resolve(undefined), TIMEOUT_MS);

    const req = http.request({
      hostname: '127.0.0.1',
      port,
      path: endpoint,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(payload) },
    }, () => {
      clearTimeout(timer);
      resolve(undefined);
    });

    req.on('error', () => {
      clearTimeout(timer);
      resolve(undefined);
    });

    req.write(payload);
    req.end();
  });
}

main().then(() => process.exit(0)).catch(() => process.exit(0));
`;

  writeFileSync(hookPath, script, 'utf-8');
  console.log(`[HookSetup] Hook script written to ${hookPath}`);
}

type HookEntry = {
  matcher?: string;
  hooks?: Array<{ type: string; command: string }>;
};

/**
 * Registers hooks in ~/.claude/settings.json so Claude Code
 * calls our script on the relevant events.
 */
export function setupClaudeSettings(): void {
  const hookPath = getHookDispatcherPath().replace(/\\/g, '/');

  const startCommand = `node "${hookPath}" start`;
  const stopCommand = `node "${hookPath}" stop`;
  const promptCommand = `node "${hookPath}" prompt`;
  const responseStopCommand = `node "${hookPath}" response-stop`;

  const claudeDir = join(homedir(), '.claude');
  mkdirSync(claudeDir, { recursive: true });

  const settingsPath = join(claudeDir, 'settings.json');

  let settings: Record<string, unknown> = {};
  if (existsSync(settingsPath)) {
    try {
      settings = JSON.parse(readFileSync(settingsPath, 'utf-8'));
    } catch {
      // Corrupted file ??preserve nothing
    }
  }

  if (!settings.hooks || typeof settings.hooks !== 'object') {
    settings.hooks = {};
  }

  const hooks = settings.hooks as Record<string, unknown>;
  let changed = false;

  changed = ensureHookEntry(hooks, 'SessionStart', startCommand) || changed;
  changed = ensureHookEntry(hooks, 'SessionEnd', stopCommand) || changed;
  changed = ensureHookEntry(hooks, 'UserPromptSubmit', promptCommand) || changed;
  changed = ensureHookEntry(hooks, 'Stop', responseStopCommand) || changed;

  if (changed) {
    writeFileSync(settingsPath, JSON.stringify(settings, null, 2), 'utf-8');
    console.log('[HookSetup] Claude settings updated with Netior hooks');
  }
}

function ensureHookEntry(
  hooks: Record<string, unknown>,
  eventName: string,
  command: string,
): boolean {
  if (!Array.isArray(hooks[eventName])) {
    hooks[eventName] = [];
  }

  const entries = hooks[eventName] as HookEntry[];

  // Already registered with the correct command
  if (entries.some((entry) => entry.hooks?.some((h) => h.command === command))) return false;

  // Registered with a stale path (same filename, different path) ??update in place
  const staleEntry = entries.find((entry) =>
    entry.hooks?.some((h) => isNetiorHookCommand(h.command)),
  );
  if (staleEntry) {
    staleEntry.hooks = staleEntry.hooks!.map((h) =>
      isNetiorHookCommand(h.command) ? { ...h, command } : h,
    );
    return true;
  }

  entries.push({
    matcher: '',
    hooks: [{ type: 'command', command }],
  });

  return true;
}

function isNetiorHookCommand(command: string): boolean {
  return KNOWN_HOOK_FILENAMES.some((filename) => command.includes(filename));
}
