import type {
  NetiorMcpToolSpec,
  NarreToolApprovalMode,
  NarreToolCategory,
  NarreToolKind,
  NarreToolMetadata,
  NetiorMcpToolProfile,
  NetiorMcpToolScope,
} from '../types/index.js';

type NetiorMcpToolSpecEntry = Omit<NetiorMcpToolSpec, 'key' | 'isMutation' | 'approvalMode'> & {
  isMutation?: boolean;
  approvalMode?: NarreToolApprovalMode;
};

export const NETIOR_MCP_TOOL_SPECS = {
  list_schemas: {
    description: 'List all schemas for a world, including attached meanings',
    category: 'types',
    kind: 'query',
    profiles: ['discovery'],
    scope: 'world',
    defaultWorldBinding: true,
  },
  create_schema: {
    description: 'Create a new schema for a world, including file template and attached meanings',
    category: 'types',
    kind: 'mutation',
    scope: 'world',
    defaultWorldBinding: true,
  },
  update_schema: {
    description: 'Update an existing schema, including file template and attached meanings',
    category: 'types',
    kind: 'mutation',
  },
  delete_schema: {
    description: 'Delete a schema',
    category: 'types',
    kind: 'mutation',
  },
  list_schema_fields: {
    description: 'List fields for a specific schema, including meaning bindings',
    category: 'types',
    kind: 'query',
  },
  create_schema_field: {
    description: 'Create a field on a schema. Use meaning_bindings when the field expresses semantic meaning; use set_field_behavior_dsl for advanced behavior.',
    category: 'types',
    kind: 'mutation',
  },
  update_schema_field: {
    description: 'Update a schema field, including meaning bindings and meaning-generated flags. Use set_field_behavior_dsl for advanced behavior.',
    category: 'types',
    kind: 'mutation',
  },
  set_field_behavior_dsl: {
    description: 'Configure an advanced schema field behavior with validated Netior DSL generated by Narre from the user domain request',
    category: 'types',
    kind: 'mutation',
    profiles: ['schema-field-behavior', 'bootstrap-execution'],
  },
  set_conditional_field_visibility: {
    description: 'Configure a field to be visible only when another field, optionally through a referenced object field, equals a specific value',
    category: 'types',
    kind: 'mutation',
    profiles: ['schema-field-behavior', 'bootstrap-execution'],
  },
  delete_schema_field: {
    description: 'Delete a schema field',
    category: 'types',
    kind: 'mutation',
  },
  reorder_schema_fields: {
    description: 'Reorder fields within a schema',
    category: 'types',
    kind: 'mutation',
  },
  list_schema_meanings: {
    description: 'List meanings attached to a schema and their field bindings',
    category: 'types',
    kind: 'query',
  },
  ensure_schema_meaning: {
    description: 'Attach a meaning to a schema and create its required binding slots',
    category: 'types',
    kind: 'mutation',
  },
  update_schema_meaning: {
    description: 'Update a schema meaning label or order',
    category: 'types',
    kind: 'mutation',
  },
  delete_schema_meaning: {
    description: 'Delete a schema meaning',
    category: 'types',
    kind: 'mutation',
  },
  update_schema_meaning_slot: {
    description: 'Bind or detach a meaning slot to a concrete schema field',
    category: 'types',
    kind: 'mutation',
  },
  list_meanings: {
    description: 'List meanings for a world',
    category: 'types',
    kind: 'query',
    profiles: ['discovery', 'bootstrap-execution'],
    scope: 'world',
    defaultWorldBinding: true,
  },
  list_meaning_categories: {
    description: 'List Meaning Category instances for a world. Meaning categories are schema-backed instances, not meaning string fields.',
    category: 'types',
    kind: 'query',
    profiles: ['discovery', 'bootstrap-execution'],
    scope: 'world',
    defaultWorldBinding: true,
  },
  get_meaning: {
    description: 'Get a meaning by ID',
    category: 'types',
    kind: 'query',
  },
  create_meaning: {
    description: 'Create an advanced custom meaning only after built-in and curated meanings are insufficient',
    category: 'types',
    kind: 'mutation',
    scope: 'world',
    defaultWorldBinding: true,
  },
  update_meaning: {
    description: 'Update a meaning. Do not mutate built-in/curated meaning meaning unless explicitly requested',
    category: 'types',
    kind: 'mutation',
  },
  delete_meaning: {
    description: 'Delete a meaning and detach it from schemas',
    category: 'types',
    kind: 'mutation',
  },
  list_meaning_catalog: {
    description: 'List built-in and curated meanings that Narre should prefer before creating custom meanings',
    category: 'types',
    kind: 'query',
    profiles: ['discovery', 'bootstrap-execution'],
    scope: 'world',
    defaultWorldBinding: true,
  },
  validate_dsl: {
    description: 'Validate a Netior DSL JSON AST expression or field behavior config',
    category: 'analysis',
    kind: 'query',
    profiles: ['discovery', 'bootstrap-execution', 'schema-field-behavior', 'interactive-view-authoring'],
    scope: 'world',
    defaultWorldBinding: true,
  },
  evaluate_dsl: {
    description: 'Evaluate a read-only Netior DSL JSON AST expression against a world context',
    category: 'analysis',
    kind: 'query',
    profiles: ['discovery', 'bootstrap-execution'],
    scope: 'world',
    defaultWorldBinding: true,
  },
  list_instances: {
    description: 'List or search instances in a world. Supports title query, schema narrowing, and property-based filters.',
    category: 'instances',
    kind: 'query',
    scope: 'world',
    defaultWorldBinding: true,
  },
  create_instance: {
    description: 'Create a new instance in a world, including body content and either an icon or a profile image source',
    category: 'instances',
    kind: 'mutation',
    scope: 'world',
    defaultWorldBinding: true,
  },
  update_instance: {
    description: 'Update an existing instance, including body content and either an icon or a profile image source',
    category: 'instances',
    kind: 'mutation',
  },
  delete_instance: {
    description: 'Delete a instance',
    category: 'instances',
    kind: 'mutation',
  },
  get_instance_properties: {
    description: 'Get the stored field values for a specific instance',
    category: 'instances',
    kind: 'query',
  },
  upsert_instance_property: {
    description: 'Set or replace a instance property value for a specific field',
    category: 'instances',
    kind: 'mutation',
  },
  delete_instance_property: {
    description: 'Delete a stored instance property value',
    category: 'instances',
    kind: 'mutation',
  },
  list_interactive_view_templates: {
    description: 'List interactive view templates available for a world, schema, or instance',
    category: 'instances',
    kind: 'query',
    profiles: ['interactive-view-authoring'],
    scope: 'world',
    defaultWorldBinding: true,
  },
  dry_run_interactive_view_template: {
    description: 'Validate an Interactive View Restricted TSX source and manifest without saving it',
    category: 'instances',
    kind: 'query',
    profiles: ['interactive-view-authoring'],
  },
  create_interactive_view_template: {
    description: 'Create an interactive view template with Restricted TSX source and manifest metadata',
    category: 'instances',
    kind: 'mutation',
    profiles: ['interactive-view-authoring'],
    scope: 'world',
    defaultWorldBinding: true,
  },
  update_interactive_view_template: {
    description: 'Update an existing interactive view template source, manifest, scope, or validation metadata',
    category: 'instances',
    kind: 'mutation',
    profiles: ['interactive-view-authoring'],
  },
  set_interactive_view_preference: {
    description: 'Set how a specific instance resolves its interactive view: inherit schema default, override with a template, or disable the view',
    category: 'instances',
    kind: 'mutation',
    profiles: ['interactive-view-authoring'],
  },
  set_interactive_view_schema_preference: {
    description: 'Set the default interactive view template inherited by instances of a schema',
    category: 'instances',
    kind: 'mutation',
    profiles: ['interactive-view-authoring'],
  },
  create_edge: {
    description: 'Create an edge between two network nodes',
    category: 'graph',
    kind: 'mutation',
  },
  get_edge: {
    description: 'Get an edge by ID',
    category: 'graph',
    kind: 'query',
  },
  update_edge: {
    description: 'Update an edge meaning binding or description',
    category: 'graph',
    kind: 'mutation',
  },
  delete_edge: {
    description: 'Delete an edge',
    category: 'graph',
    kind: 'mutation',
  },
  list_directory: {
    displayName: 'Browse Directory',
    description: 'List contents of a directory within registered module paths',
    category: 'files',
    kind: 'query',
    profiles: ['bootstrap-skill', 'bootstrap-interview', 'bootstrap-execution'],
    scope: 'world',
    defaultWorldBinding: true,
  },
  read_file: {
    displayName: 'Read File',
    description: 'Read contents of a file within registered module paths',
    category: 'files',
    kind: 'query',
    profiles: ['bootstrap-skill', 'bootstrap-interview', 'bootstrap-execution'],
    scope: 'world',
    defaultWorldBinding: true,
  },
  glob_files: {
    displayName: 'Find Files',
    description: 'Find files matching a glob pattern within registered module paths',
    category: 'search',
    kind: 'query',
    profiles: ['bootstrap-skill', 'bootstrap-interview', 'bootstrap-execution'],
    scope: 'world',
    defaultWorldBinding: true,
  },
  grep_files: {
    displayName: 'Search File Contents',
    description: 'Search file contents with a regex pattern within registered module paths',
    category: 'search',
    kind: 'analysis',
    profiles: ['bootstrap-skill', 'bootstrap-interview', 'bootstrap-execution'],
    scope: 'world',
    defaultWorldBinding: true,
  },
  list_modules: {
    description: 'List all modules for a world',
    category: 'modules',
    kind: 'query',
    profiles: ['discovery'],
    scope: 'world',
    defaultWorldBinding: true,
  },
  get_field_candidates: {
    displayName: 'Suggest Field Options',
    description: 'Get candidate values or candidate instances for a field definition. Use this before assigning relational or choice values.',
    category: 'types',
    kind: 'analysis',
    scope: 'world',
    defaultWorldBinding: true,
  },
  create_network_node: {
    description: 'Create a node in a network for an existing object record, including optional node type and structured node config metadata',
    category: 'graph',
    kind: 'mutation',
  },
  update_network_node: {
    description: 'Update a network node type, parent, raw metadata, or structured node config',
    category: 'graph',
    kind: 'mutation',
  },
  delete_network_node: {
    description: 'Delete a network node',
    category: 'graph',
    kind: 'mutation',
  },
  list_networks: {
    description: 'List networks in a world',
    category: 'graph',
    kind: 'query',
    profiles: ['discovery'],
    scope: 'world',
    defaultWorldBinding: true,
  },
  create_network: {
    description: 'Create a network for graph organization and navigation',
    category: 'graph',
    kind: 'mutation',
    scope: 'world',
    defaultWorldBinding: true,
  },
  update_network: {
    description: 'Update a network name, scope, or parent',
    category: 'graph',
    kind: 'mutation',
  },
  delete_network: {
    description: 'Delete a network',
    category: 'graph',
    kind: 'mutation',
  },
  get_network_full: {
    displayName: 'Inspect Network',
    description: 'Get a network with nodes, edges, objects, and layout references',
    category: 'graph',
    kind: 'query',
  },
  get_universe_network: {
    description: 'Get the Universe network',
    category: 'graph',
    kind: 'query',
    profiles: ['discovery'],
    scope: 'app',
  },
  get_root_network: {
    description: 'Get the Root network for a world',
    category: 'graph',
    kind: 'query',
    profiles: ['discovery'],
    scope: 'world',
    defaultWorldBinding: true,
  },
  get_network_tree: {
    displayName: 'Browse Network Tree',
    description: 'Get the network hierarchy tree for a world',
    category: 'graph',
    kind: 'query',
    profiles: ['discovery'],
    scope: 'world',
    defaultWorldBinding: true,
  },
  get_network_ancestors: {
    description: 'Get breadcrumb ancestors for a network',
    category: 'graph',
    kind: 'query',
  },
  list_network_representation_primitives: {
    description: 'List system-fixed network representation primitives and surface runtimes',
    category: 'graph',
    kind: 'query',
    profiles: ['discovery', 'bootstrap-execution', 'network-representation-authoring'],
    scope: 'world',
    defaultWorldBinding: true,
  },
  list_network_types: {
    description: 'List built-in and world network types, including surface runtime keys',
    category: 'graph',
    kind: 'query',
    profiles: ['discovery', 'bootstrap-execution', 'network-representation-authoring'],
    scope: 'world',
    defaultWorldBinding: true,
  },
  get_network_type: {
    description: 'Get a network type grammar by ID',
    category: 'graph',
    kind: 'query',
    profiles: ['network-representation-authoring', 'discovery', 'bootstrap-execution'],
  },
  create_network_type: {
    description: 'Create a user-defined network type grammar from system representation primitives',
    category: 'graph',
    kind: 'mutation',
    profiles: ['network-representation-authoring', 'bootstrap-execution'],
    scope: 'world',
    defaultWorldBinding: true,
  },
  update_network_type: {
    description: 'Update a user-defined network type grammar',
    category: 'graph',
    kind: 'mutation',
    profiles: ['network-representation-authoring', 'bootstrap-execution'],
  },
  delete_network_type: {
    description: 'Delete a user-defined network type grammar',
    category: 'graph',
    kind: 'mutation',
    profiles: ['network-representation-authoring', 'bootstrap-execution'],
  },
  list_node_types: {
    description: 'List representation node types for a network type',
    category: 'graph',
    kind: 'query',
    profiles: ['network-representation-authoring', 'discovery', 'bootstrap-execution'],
  },
  create_node_type: {
    description: 'Create a representation node type inside a network type',
    category: 'graph',
    kind: 'mutation',
    profiles: ['network-representation-authoring', 'bootstrap-execution'],
  },
  update_node_type: {
    description: 'Update a representation node type',
    category: 'graph',
    kind: 'mutation',
    profiles: ['network-representation-authoring', 'bootstrap-execution'],
  },
  delete_node_type: {
    description: 'Delete a user-defined representation node type',
    category: 'graph',
    kind: 'mutation',
    profiles: ['network-representation-authoring', 'bootstrap-execution'],
  },
  list_edge_types: {
    description: 'List representation edge types for a network type',
    category: 'graph',
    kind: 'query',
    profiles: ['network-representation-authoring', 'discovery', 'bootstrap-execution'],
  },
  create_edge_type: {
    description: 'Create a representation edge type inside a network type',
    category: 'graph',
    kind: 'mutation',
    profiles: ['network-representation-authoring', 'bootstrap-execution'],
  },
  update_edge_type: {
    description: 'Update a representation edge type',
    category: 'graph',
    kind: 'mutation',
    profiles: ['network-representation-authoring', 'bootstrap-execution'],
  },
  delete_edge_type: {
    description: 'Delete a user-defined representation edge type',
    category: 'graph',
    kind: 'mutation',
    profiles: ['network-representation-authoring', 'bootstrap-execution'],
  },
  list_relationships: {
    description: 'List world-level object relationships independent of network occurrence',
    category: 'graph',
    kind: 'query',
    profiles: ['discovery', 'bootstrap-execution'],
    scope: 'world',
    defaultWorldBinding: true,
  },
  get_relationship: {
    description: 'Get a world-level object relationship by ID',
    category: 'graph',
    kind: 'query',
  },
  create_relationship: {
    description: 'Create a world-level relationship between two object records',
    category: 'graph',
    kind: 'mutation',
    scope: 'world',
    defaultWorldBinding: true,
  },
  update_relationship: {
    description: 'Update a world-level object relationship meaning or metadata',
    category: 'graph',
    kind: 'mutation',
  },
  delete_relationship: {
    description: 'Delete a world-level object relationship',
    category: 'graph',
    kind: 'mutation',
  },
  list_relationship_occurrences: {
    description: 'List network edge occurrences that represent a relationship',
    category: 'graph',
    kind: 'query',
  },
  get_object: {
    displayName: 'Inspect Object',
    description: 'Get a network object record by object ID',
    category: 'graph',
    kind: 'query',
  },
  get_object_by_ref: {
    displayName: 'Find Object by Reference',
    description: 'Get a network object record from a domain object type and ref ID',
    category: 'graph',
    kind: 'query',
  },
  read_pdf_pages: {
    displayName: 'Read PDF Pages',
    description: 'Extract text from specified page range of a PDF file. Use this to read TOC pages for indexing.',
    category: 'files',
    kind: 'analysis',
    profiles: ['index-skill'],
    scope: 'world',
    defaultWorldBinding: true,
  },
  read_pdf_pages_vision: {
    displayName: 'Read PDF with Vision',
    description: '[Experimental -- requires optional "canvas" npm package] Render PDF pages as images for vision-based TOC extraction. Will error if canvas is not installed. Not used by default prompts.',
    category: 'files',
    kind: 'analysis',
    profiles: ['index-skill'],
    scope: 'world',
    defaultWorldBinding: true,
  },
  get_file_metadata: {
    displayName: 'Read File Metadata',
    description: 'Get a file entity and its metadata from the database. Use this to check if a PDF already has a TOC.',
    category: 'files',
    kind: 'query',
    profiles: ['index-skill'],
    scope: 'file',
  },
  update_file_pdf_toc: {
    displayName: 'Update PDF Table of Contents',
    description: 'Save or update the PDF table of contents for a file entity. Only call this after the user has approved the TOC.',
    category: 'files',
    kind: 'mutation',
    profiles: ['index-skill'],
    scope: 'file',
  },
  get_world_summary: {
    displayName: 'World Summary',
    description: 'Get a summary of a world including schema, meaning, instance, and network context',
    category: 'world',
    kind: 'analysis',
    profiles: ['discovery'],
    scope: 'world',
    defaultWorldBinding: true,
  },
} as const satisfies Record<string, NetiorMcpToolSpecEntry>;

export type NetiorMcpToolKey = keyof typeof NETIOR_MCP_TOOL_SPECS;
export const DEFAULT_NETIOR_MCP_TOOL_PROFILE: NetiorMcpToolProfile = 'core';

function humanizeToolName(toolName: string): string {
  return toolName
    .split('_')
    .filter(Boolean)
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join(' ');
}

function inferToolCategory(toolName: string): NarreToolCategory {
  if (toolName.includes('schema') || toolName.includes('meaning') || toolName.includes('field')) {
    return 'types';
  }
  if (toolName.includes('instance')) {
    return 'instances';
  }
  if (toolName.includes('network') || toolName.includes('edge') || toolName.includes('object') || toolName.includes('node')) {
    return 'graph';
  }
  if (toolName.includes('module')) {
    return 'modules';
  }
  if (toolName.includes('file') || toolName.includes('directory') || toolName.includes('pdf')) {
    return 'files';
  }
  if (toolName.includes('search') || toolName.includes('glob') || toolName.includes('grep')) {
    return 'search';
  }
  if (toolName.includes('world')) {
    return 'world';
  }
  return 'analysis';
}

function inferToolKind(toolName: string): NarreToolKind {
  if (/^(create|update|delete|upsert|reorder)_/.test(toolName)) {
    return 'mutation';
  }
  if (/^(read|list|get)_/.test(toolName)) {
    return 'query';
  }
  return 'analysis';
}

function inferToolScope(toolName: string): NetiorMcpToolScope {
  if (toolName === 'get_universe_network') {
    return 'app';
  }
  if (toolName.includes('object')) {
    return 'object';
  }
  if (toolName.includes('network') || toolName.includes('edge') || toolName.includes('node')) {
    return 'network';
  }
  if (toolName.includes('file') || toolName.includes('pdf')) {
    return 'file';
  }
  if (
    toolName.includes('world')
    || toolName.includes('schema')
    || toolName.includes('meaning')
    || toolName.includes('instance')
    || toolName.includes('module')
  ) {
    return 'world';
  }
  return 'mixed';
}

function buildToolSpec(toolName: string, entry: NetiorMcpToolSpecEntry): NetiorMcpToolSpec {
  const isMutation = entry.isMutation ?? entry.kind === 'mutation';
  return {
    key: toolName,
    ...(entry.displayName ? { displayName: entry.displayName } : {}),
    description: entry.description,
    category: entry.category,
    kind: entry.kind,
    isMutation,
    approvalMode: entry.approvalMode ?? (isMutation ? 'prompt' : 'auto'),
    profiles: entry.profiles ?? [DEFAULT_NETIOR_MCP_TOOL_PROFILE],
    scope: entry.scope ?? inferToolScope(toolName),
    defaultWorldBinding: entry.defaultWorldBinding ?? false,
  };
}

export function normalizeNetiorToolName(toolName: string): string {
  const trimmed = toolName.trim();
  if (!trimmed) {
    return trimmed;
  }

  const lastSegment = trimmed.split('.').at(-1) ?? trimmed;
  return lastSegment.trim();
}

export function hasNetiorMcpToolSpec(toolName: string): toolName is NetiorMcpToolKey {
  return Object.prototype.hasOwnProperty.call(NETIOR_MCP_TOOL_SPECS, normalizeNetiorToolName(toolName));
}

export function getNetiorMcpToolSpec(toolName: NetiorMcpToolKey): NetiorMcpToolSpec;
export function getNetiorMcpToolSpec(toolName: string): NetiorMcpToolSpec | null;
export function getNetiorMcpToolSpec(toolName: string): NetiorMcpToolSpec | null {
  const normalizedToolName = normalizeNetiorToolName(toolName);
  if (!hasNetiorMcpToolSpec(normalizedToolName)) {
    return null;
  }

  return buildToolSpec(normalizedToolName, NETIOR_MCP_TOOL_SPECS[normalizedToolName]);
}

export function listNetiorMcpToolSpecs(): NetiorMcpToolSpec[] {
  return Object.entries(NETIOR_MCP_TOOL_SPECS).map(([toolName, entry]) => buildToolSpec(toolName, entry));
}

export function isNetiorMcpToolEnabledForProfile(toolName: string, profile: NetiorMcpToolProfile): boolean {
  const spec = getNetiorMcpToolSpec(toolName);
  if (!spec) {
    return false;
  }

  const profiles = spec.profiles ?? [DEFAULT_NETIOR_MCP_TOOL_PROFILE];
  return profiles.includes(profile);
}

export function getNarreToolMetadata(toolName: string): NarreToolMetadata {
  const normalizedToolName = normalizeNetiorToolName(toolName);
  const spec = getNetiorMcpToolSpec(normalizedToolName);
  if (spec) {
    return {
      displayName: spec.displayName ?? humanizeToolName(spec.key),
      description: spec.description,
      category: spec.category,
      kind: spec.kind,
      isMutation: spec.isMutation,
      approvalMode: spec.approvalMode,
      profiles: spec.profiles,
      scope: spec.scope,
      defaultWorldBinding: spec.defaultWorldBinding,
    };
  }

  const kind = inferToolKind(normalizedToolName);
  return {
    displayName: humanizeToolName(normalizedToolName),
    category: inferToolCategory(normalizedToolName),
    kind,
    isMutation: kind === 'mutation',
    approvalMode: kind === 'mutation' ? 'prompt' : 'auto',
    profiles: [DEFAULT_NETIOR_MCP_TOOL_PROFILE],
    scope: inferToolScope(normalizedToolName),
    defaultWorldBinding: false,
  };
}
