import type { ShortcutDefinition } from './shortcut-types';

export const SHORTCUT_REGISTRY: ShortcutDefinition[] = [
  {
    id: 'shortcut.global.saveActiveTab',
    labelKey: 'shortcuts.items.global.saveActiveTabLabel',
    descriptionKey: 'shortcuts.items.global.saveActiveTab',
    keybinding: 'Ctrl/Cmd+S',
    scope: 'global',
    owner: 'globalDispatcher',
    priority: 'global',
    implemented: true,
  },
  {
    id: 'shortcut.global.closeActiveTab',
    labelKey: 'shortcuts.items.global.closeActiveTabLabel',
    descriptionKey: 'shortcuts.items.global.closeActiveTab',
    keybinding: 'Ctrl/Cmd+W',
    scope: 'global',
    owner: 'globalDispatcher',
    priority: 'global',
    implemented: true,
  },
  {
    id: 'shortcut.global.openSettings',
    labelKey: 'shortcuts.items.global.openSettingsLabel',
    descriptionKey: 'shortcuts.items.global.openSettings',
    keybinding: 'Ctrl/Cmd+,',
    scope: 'global',
    owner: 'globalDispatcher',
    priority: 'global',
    implemented: true,
  },
  {
    id: 'shortcut.global.openShortcutOverlay',
    labelKey: 'shortcuts.items.global.openShortcutOverlayLabel',
    descriptionKey: 'shortcuts.items.global.openShortcutOverlay',
    keybinding: 'Ctrl/Cmd+/',
    scope: 'global',
    owner: 'globalDispatcher',
    priority: 'global',
    implemented: true,
  },
  {
    id: 'shortcut.global.toggleSidebar',
    labelKey: 'shortcuts.items.global.toggleSidebarLabel',
    descriptionKey: 'shortcuts.items.global.toggleSidebar',
    keybinding: 'Ctrl/Cmd+B',
    scope: 'global',
    owner: 'globalDispatcher',
    priority: 'global',
    implemented: true,
  },
  {
    id: 'shortcut.global.openTerminal',
    labelKey: 'shortcuts.items.global.openTerminalLabel',
    descriptionKey: 'shortcuts.items.global.openTerminal',
    keybinding: 'Ctrl/Cmd+Shift+N',
    scope: 'global',
    owner: 'globalDispatcher',
    priority: 'global',
    implemented: true,
  },
  {
    id: 'shortcut.global.openBrowser',
    labelKey: 'shortcuts.items.global.openBrowserLabel',
    descriptionKey: 'shortcuts.items.global.openBrowser',
    keybinding: 'Ctrl/Cmd+Shift+B',
    scope: 'global',
    owner: 'globalDispatcher',
    priority: 'global',
    implemented: true,
  },
  {
    id: 'shortcut.global.openNarre',
    labelKey: 'shortcuts.items.global.openNarreLabel',
    descriptionKey: 'shortcuts.items.global.openNarre',
    keybinding: 'Ctrl/Cmd+Alt+N',
    scope: 'global',
    owner: 'globalDispatcher',
    priority: 'global',
    implemented: true,
    whenKey: 'shortcuts.when.worldOpen',
  },
  {
    id: 'shortcut.global.nextTab',
    labelKey: 'shortcuts.items.global.nextTabLabel',
    descriptionKey: 'shortcuts.items.global.nextTab',
    keybinding: 'Ctrl/Cmd+Tab',
    scope: 'global',
    owner: 'globalDispatcher',
    priority: 'global',
    implemented: true,
  },
  {
    id: 'shortcut.global.previousTab',
    labelKey: 'shortcuts.items.global.previousTabLabel',
    descriptionKey: 'shortcuts.items.global.previousTab',
    keybinding: 'Ctrl/Cmd+Shift+Tab',
    scope: 'global',
    owner: 'globalDispatcher',
    priority: 'global',
    implemented: true,
  },
  {
    id: 'shortcut.global.openTabByIndex',
    labelKey: 'shortcuts.items.global.openTabByIndexLabel',
    descriptionKey: 'shortcuts.items.global.openTabByIndex',
    keybinding: 'Ctrl/Cmd+1..9',
    scope: 'global',
    owner: 'globalDispatcher',
    priority: 'global',
    implemented: true,
  },
  {
    id: 'shortcut.global.jumpToLastAgent',
    labelKey: 'shortcuts.items.global.jumpToLastAgentLabel',
    descriptionKey: 'shortcuts.items.global.jumpToLastAgent',
    keybinding: 'Ctrl/Cmd+.',
    scope: 'global',
    owner: 'globalDispatcher',
    priority: 'global',
    implemented: true,
  },
  {
    id: 'shortcut.global.nextPane',
    labelKey: 'shortcuts.items.global.nextPaneLabel',
    descriptionKey: 'shortcuts.items.global.nextPane',
    keybinding: 'Ctrl/Cmd+Alt+]',
    scope: 'global',
    owner: 'globalDispatcher',
    priority: 'global',
    implemented: true,
  },
  {
    id: 'shortcut.global.previousPane',
    labelKey: 'shortcuts.items.global.previousPaneLabel',
    descriptionKey: 'shortcuts.items.global.previousPane',
    keybinding: 'Ctrl/Cmd+Alt+[',
    scope: 'global',
    owner: 'globalDispatcher',
    priority: 'global',
    implemented: true,
  },
  {
    id: 'shortcut.global.toggleToc',
    labelKey: 'shortcuts.items.global.toggleTocLabel',
    descriptionKey: 'shortcuts.items.global.toggleToc',
    keybinding: 'Ctrl/Cmd+Shift+O',
    scope: 'global',
    owner: 'globalDispatcher',
    priority: 'global',
    implemented: true,
  },
  {
    id: 'shortcut.global.toggleEditorMode',
    labelKey: 'shortcuts.items.global.toggleEditorModeLabel',
    descriptionKey: 'shortcuts.items.global.toggleEditorMode',
    keybinding: 'Ctrl/Cmd+\\',
    scope: 'global',
    owner: 'globalDispatcher',
    priority: 'global',
    implemented: true,
  },
  {
    id: 'shortcut.fileTree.openSelection',
    labelKey: 'shortcuts.items.fileTree.openSelectionLabel',
    descriptionKey: 'shortcuts.items.fileTree.openSelection',
    keybinding: 'Enter',
    scope: 'fileTree',
    owner: 'fileTree',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.fileTree.renameSelection',
    labelKey: 'shortcuts.items.fileTree.renameSelectionLabel',
    descriptionKey: 'shortcuts.items.fileTree.renameSelection',
    keybinding: 'F2',
    scope: 'fileTree',
    owner: 'fileTree',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.fileTree.deleteSelection',
    labelKey: 'shortcuts.items.fileTree.deleteSelectionLabel',
    descriptionKey: 'shortcuts.items.fileTree.deleteSelection',
    keybinding: 'Delete',
    scope: 'fileTree',
    owner: 'fileTree',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.fileTree.copySelection',
    labelKey: 'shortcuts.items.fileTree.copySelectionLabel',
    descriptionKey: 'shortcuts.items.fileTree.copySelection',
    keybinding: 'Ctrl/Cmd+C',
    scope: 'fileTree',
    owner: 'fileTree',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.fileTree.cutSelection',
    labelKey: 'shortcuts.items.fileTree.cutSelectionLabel',
    descriptionKey: 'shortcuts.items.fileTree.cutSelection',
    keybinding: 'Ctrl/Cmd+X',
    scope: 'fileTree',
    owner: 'fileTree',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.fileTree.pasteIntoSelection',
    labelKey: 'shortcuts.items.fileTree.pasteIntoSelectionLabel',
    descriptionKey: 'shortcuts.items.fileTree.pasteIntoSelection',
    keybinding: 'Ctrl/Cmd+V',
    scope: 'fileTree',
    owner: 'fileTree',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.network.selectAllNodes',
    labelKey: 'shortcuts.items.network.selectAllNodesLabel',
    descriptionKey: 'shortcuts.items.network.selectAllNodes',
    keybinding: 'Ctrl/Cmd+A',
    scope: 'network',
    owner: 'networkContext',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.network.deleteSelection',
    labelKey: 'shortcuts.items.network.deleteSelectionLabel',
    descriptionKey: 'shortcuts.items.network.deleteSelection',
    keybinding: 'Delete',
    scope: 'network',
    owner: 'networkContext',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.network.cancelLinking',
    labelKey: 'shortcuts.items.network.cancelLinkingLabel',
    descriptionKey: 'shortcuts.items.network.cancelLinking',
    keybinding: 'Escape',
    scope: 'network',
    owner: 'networkContext',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.network.toggleMode',
    labelKey: 'shortcuts.items.network.toggleModeLabel',
    descriptionKey: 'shortcuts.items.network.toggleMode',
    keybinding: 'E',
    scope: 'network',
    owner: 'networkContext',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.network.fitToScreen',
    labelKey: 'shortcuts.items.network.fitToScreenLabel',
    descriptionKey: 'shortcuts.items.network.fitToScreen',
    keybinding: 'F',
    scope: 'network',
    owner: 'networkContext',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.terminal.openSearch',
    labelKey: 'shortcuts.items.terminal.openSearchLabel',
    descriptionKey: 'shortcuts.items.terminal.openSearch',
    keybinding: 'Ctrl/Cmd+F',
    scope: 'terminal',
    owner: 'terminalEditor',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.terminal.copySelection',
    labelKey: 'shortcuts.items.terminal.copySelectionLabel',
    descriptionKey: 'shortcuts.items.terminal.copySelection',
    keybinding: 'Ctrl/Cmd+C',
    scope: 'terminal',
    owner: 'terminalEditor',
    priority: 'context',
    implemented: true,
    whenKey: 'shortcuts.when.selectionExists',
  },
  {
    id: 'shortcut.terminal.paste',
    labelKey: 'shortcuts.items.terminal.pasteLabel',
    descriptionKey: 'shortcuts.items.terminal.paste',
    keybinding: 'Ctrl/Cmd+V',
    scope: 'terminal',
    owner: 'terminalEditor',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.terminal.fontSizeUp',
    labelKey: 'shortcuts.items.terminal.fontSizeUpLabel',
    descriptionKey: 'shortcuts.items.terminal.fontSizeUp',
    keybinding: 'Ctrl/Cmd+=',
    scope: 'terminal',
    owner: 'terminalEditor',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.terminal.fontSizeDown',
    labelKey: 'shortcuts.items.terminal.fontSizeDownLabel',
    descriptionKey: 'shortcuts.items.terminal.fontSizeDown',
    keybinding: 'Ctrl/Cmd+-',
    scope: 'terminal',
    owner: 'terminalEditor',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.terminal.fontSizeReset',
    labelKey: 'shortcuts.items.terminal.fontSizeResetLabel',
    descriptionKey: 'shortcuts.items.terminal.fontSizeReset',
    keybinding: 'Ctrl/Cmd+0',
    scope: 'terminal',
    owner: 'terminalEditor',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.terminal.pageScrollUp',
    labelKey: 'shortcuts.items.terminal.pageScrollUpLabel',
    descriptionKey: 'shortcuts.items.terminal.pageScrollUp',
    keybinding: 'Shift+PageUp',
    scope: 'terminal',
    owner: 'terminalEditor',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.terminal.pageScrollDown',
    labelKey: 'shortcuts.items.terminal.pageScrollDownLabel',
    descriptionKey: 'shortcuts.items.terminal.pageScrollDown',
    keybinding: 'Shift+PageDown',
    scope: 'terminal',
    owner: 'terminalEditor',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.narreChat.sendMessage',
    labelKey: 'shortcuts.items.narreChat.sendMessageLabel',
    descriptionKey: 'shortcuts.items.narreChat.sendMessage',
    keybinding: 'Enter',
    scope: 'narreChat',
    owner: 'narreChat',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.narreChat.insertNewline',
    labelKey: 'shortcuts.items.narreChat.insertNewlineLabel',
    descriptionKey: 'shortcuts.items.narreChat.insertNewline',
    keybinding: 'Shift+Enter',
    scope: 'narreChat',
    owner: 'narreChat',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.narreMentionPicker.selectNext',
    labelKey: 'shortcuts.items.narreMentionPicker.selectNextLabel',
    descriptionKey: 'shortcuts.items.narreMentionPicker.selectNext',
    keybinding: 'ArrowDown',
    scope: 'narreMentionPicker',
    owner: 'narreMentionPicker',
    priority: 'local',
    implemented: true,
  },
  {
    id: 'shortcut.narreMentionPicker.selectPrevious',
    labelKey: 'shortcuts.items.narreMentionPicker.selectPreviousLabel',
    descriptionKey: 'shortcuts.items.narreMentionPicker.selectPrevious',
    keybinding: 'ArrowUp',
    scope: 'narreMentionPicker',
    owner: 'narreMentionPicker',
    priority: 'local',
    implemented: true,
  },
  {
    id: 'shortcut.narreMentionPicker.confirmSelection',
    labelKey: 'shortcuts.items.narreMentionPicker.confirmSelectionLabel',
    descriptionKey: 'shortcuts.items.narreMentionPicker.confirmSelection',
    keybinding: 'Enter',
    scope: 'narreMentionPicker',
    owner: 'narreMentionPicker',
    priority: 'local',
    implemented: true,
  },
  {
    id: 'shortcut.narreMentionPicker.close',
    labelKey: 'shortcuts.items.narreMentionPicker.closeLabel',
    descriptionKey: 'shortcuts.items.narreMentionPicker.close',
    keybinding: 'Escape',
    scope: 'narreMentionPicker',
    owner: 'narreMentionPicker',
    priority: 'local',
    implemented: true,
  },
  {
    id: 'shortcut.narreSlashPicker.selectNext',
    labelKey: 'shortcuts.items.narreSlashPicker.selectNextLabel',
    descriptionKey: 'shortcuts.items.narreSlashPicker.selectNext',
    keybinding: 'ArrowDown',
    scope: 'narreSlashPicker',
    owner: 'narreSlashPicker',
    priority: 'local',
    implemented: true,
  },
  {
    id: 'shortcut.narreSlashPicker.selectPrevious',
    labelKey: 'shortcuts.items.narreSlashPicker.selectPreviousLabel',
    descriptionKey: 'shortcuts.items.narreSlashPicker.selectPrevious',
    keybinding: 'ArrowUp',
    scope: 'narreSlashPicker',
    owner: 'narreSlashPicker',
    priority: 'local',
    implemented: true,
  },
  {
    id: 'shortcut.narreSlashPicker.confirmSelection',
    labelKey: 'shortcuts.items.narreSlashPicker.confirmSelectionLabel',
    descriptionKey: 'shortcuts.items.narreSlashPicker.confirmSelection',
    keybinding: 'Enter',
    scope: 'narreSlashPicker',
    owner: 'narreSlashPicker',
    priority: 'local',
    implemented: true,
  },
  {
    id: 'shortcut.narreSlashPicker.close',
    labelKey: 'shortcuts.items.narreSlashPicker.closeLabel',
    descriptionKey: 'shortcuts.items.narreSlashPicker.close',
    keybinding: 'Escape',
    scope: 'narreSlashPicker',
    owner: 'narreSlashPicker',
    priority: 'local',
    implemented: true,
  },
];

export function getShortcutDefinition(id: string): ShortcutDefinition | undefined {
  return SHORTCUT_REGISTRY.find((shortcut) => shortcut.id === id);
}
